/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical projects. It is checked in here so
// TypeScript understands Next-specific globals before the first local dev run.
